services:
  http-server-projeto-korp:
    build: ../server
    networks:
      - projeto-korp
  nginx:
    image: nginx:stable-bookworm
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ../proxy/http-server-projeto-korp.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    networks:
      - projeto-korp
    depends_on:
      - server

networks:
  projeto-korp:
    driver: bridge