- name: Desafio Técnico - Viasoft Korp
  hosts: localhost
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Get services list
      ansible.builtin.service_facts:
    
    - name: Install docker
      when: ansible_facts['services']['docker.service']['status'] | default('not-found') == 'not-found'
      block:
        - name: Include update packages tasks
          ansible.builtin.include_tasks: update_packages.yml

        - name: Install certificates and curl
          ansible.builtin.apt:
            pkg:
            - ca-certificates
            - curl

        - name: Download official gpg key to install docker
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/keyrings/docker.asc
        
        - name: Change file mode
          ansible.builtin.file:
            path: /etc/apt/keyrings/docker.asc
            mode: a+r

        - name: Add repository to apt
          ansible.builtin.shell: |
           echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
           $(. /etc/os-release && echo \"${UBUNTU_CODENAME:-$VERSION_CODENAME}\") stable" > /etc/apt/sources.list.d/docker.list
          args:
            chdir: ~/

        - name: Include update packages tasks
          ansible.builtin.include_tasks: update_packages.yml

        - name: Install docker packages
          ansible.builtin.apt:
            pkg:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-buildx-plugin
            - docker-compose-plugin
        
        - name: Create docker group to grant root privileges
          ansible.builtin.group:
            name: docker
            state: present
        
        - name: Add user to docker group
          ansible.builtin.user:
            name: "{{ lookup('env', 'USER') }}"
            groups: docker
            append: true
          register: result

    - name: Install Go
      block:
        - name: Download Go file
          ansible.builtin.get_url:
            url: https://golang.org/dl/go1.24.4.linux-amd64.tar.gz
            dest: /tmp

        - name: Extract and move go to /usr/local
          ansible.builtin.unarchive:
            src: /tmp/go1.24.4.linux-amd64.tar.gz
            dest: /usr/local

        - name: Add go binary to path
          ansible.builtin.lineinfile:
            path: ~/.bashrc
            line: 'export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin'
            create: true
            state: present
        
        - name: Update source
          ansible.builtin.shell:
            cmd: . ~/.bashrc
            chdir: ~/

    
    - name: Install required modules
      ansible.builtin.shell: 
        cmd: /usr/local/go/bin/go install
        chdir: ../server/cmd

    - name: Compile server service
      ansible.builtin.shell: 
        cmd: /usr/local/go/bin/go build -o http-server-projeto-korp main.go
        chdir: ../server/cmd

    - name: Init services
      block:
        - name: Create and start services
          ansible.builtin.shell:
            cmd: docker compose up -d
            chdir: ../docker
          register: output

        - name: Show output
          ansible.builtin.debug:
            var: output

    - name: Test service
      ansible.builtin.uri:
        url: http://localhost:80
      register: response

    - name: Show service response
      ansible.builtin.debug:
        var: response.json