- name: Desafio Técnico - Viasoft Korp
  hosts: localhost

  tasks:
    - name: Get services list
      ansible.builtin.service_facts:
    
    - name: Install docker
      when: ansible_facts['services']['docker.service']['status'] | default('not-found') == 'not-found'
      block:
        - name: Download official script to install docker
          ansible.builtin.get_url:
            url: https://get.docker.com
            dest: /tmp/get-docker.sh
        
        - name: Create docker group to grant root privileges
          ansible.builtin.group:
            name: docker
            state: present
        
        - name: Add user to docker group
          ansible.builtin.user:
            name: "{{ lookup('env', 'USER') }}"
            groups: docker
            append: true
          register: result

        - name: Include reset connection tasks
          ansible.builtin.include_tasks: reset_connection.yml
          when: result.changed == true

    - name: Install Go
      block:
        - name: Download Go file
          ansible.builtin.get_url:
            url: https://golang.org/dl/go1.24.4.linux-amd64.tar.gz
            dest: /tmp

        - name: Extract and move go to /usr/local
          ansible.builtin.unarchive:
            src: /tmp/go1.24.4.linux-amd64.tar.gz
            dest: /usr/local

        - name: Add go binary to path
          ansible.builtin.lineinfile:
            path: ~/.bashrc
            line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
            create: true
            state: present
        
        - name: Update source and test go version
          ansible.builtin.shell: source ~/.bashrc && go version

    - name: Compile server service
      ansible.builtin.command: go build -o http-server-projeto-korp main.go
      args:
        chdir: server

    - name: Init services
      block:
        - name: Delete all existing services
          community.docker.docker_compose_v2:
            project_src: ../docker
            state: absent
        
        - name: Create and start services
          community.docker.docker_compose_v2:
            project_src: ../docker
          register: output

        - name: Show output
          ansible.builtin.debug:
            var: output

    - name: Test service
      ansible.builtin.uri:
        url: http://localhost:80
      register: response

    - name: Show service response
      ansible.builtin.debug:
        var: response